# Bind to all interfaces inside the docker network
bind 0.0.0.0

# Protect mode is useful if exposed to the internet, but we are inside docker internal network
protected-mode yes

# Require password (set via env or here, but it's better to use CLI argument --requirepass in compose)
# We will use compose command to set requirepass securely using env vars.

# Disable dangerous commands
rename-command FLUSHDB ""
rename-command FLUSHALL ""
rename-command DEBUG ""
rename-command CONFIG ""

# Persistence
appendonly yes
appendfsync everysec
